name: Tests
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: test-${{ hashFiles('deps.edn') }}
          restore-keys: test-
      - run: clojure -X:dev:test
      - run: clojure -X:dev:doc
      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
